/**
 * Exports the item catalog to a flat CSV and a grouped Markdown table.
 *
 * Run with:  npm run catalog
 *
 * Output:
 *   catalog/items.csv  — one row per item, every static field as a column.
 *                       Open in Excel/Numbers/Sheets for balance review.
 *   catalog/items.md   — same data grouped by nature type, easy to read.
 *
 * Re-run any time you tweak items.ts; the files are overwritten cleanly.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ITEMS } from "../src/data/items";
import {
  EFFECT_TABLE, VAMPIRISM_PCT,
  BURN_TICK_DPS, POISON_TICK_DPS, REGEN_PER_SEC,
  SLOWING_SEC, FASTING_SEC, RECHARGE_SEC,
} from "../src/data/scaling";
import { hasItemSprite, hasHeroSprite } from "../src/data/spritesManifest";
import { HEROES } from "../src/data/heroes";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "catalog");

// ─── CSV columns (in order) ─────────────────────────────────────────────────
const COLS = [
  "id",
  "name",
  "nature_type",
  "size",
  "min_rarity",
  "max_rarity",
  "base_cooldown_s",
  "keywords",
  "carries_damage",
  "carries_shield",
  "carries_healing",
  "carries_overhealing",
  "vampirism_pct_at_silver",
  "burn_stacks",
  "poison_stacks",
  "regen_per_sec",
  "slowing_sec_at_silver",
  "recharge_sec_at_silver",
  "fasting_sec_at_silver",
  "link_direction",
  "link_damage",
  "link_shield",
  "link_healing_pct",
  "link_vampirism_pct",
  "link_cd_reduction_pct",
  "link_global_target",
  "heavy",
  "sprite_path",
  "has_sprite_png",
  "description",
];

function csvEscape(v: unknown): string {
  if (v === undefined || v === null) return "";
  const s = String(v);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function rowFor(it: typeof ITEMS[number]): unknown[] {
  const k = it.keywords;
  const e = it.baseEffects;
  const l = it.link;
  return [
    it.id,
    it.name,
    it.natureType,
    it.size,
    it.minRarity,
    it.maxRarity,
    it.baseCooldown >= 100 ? "passive" : it.baseCooldown,
    k.join(";"),
    k.includes("Damage") ? 1 : 0,
    k.includes("Shield") ? 1 : 0,
    k.includes("Healing") ? 1 : 0,
    k.includes("Overhealing") ? 1 : 0,
    k.includes("Vampirism") ? VAMPIRISM_PCT.Silver : "",
    e.burnStacks ?? "",
    e.poisonStacks ?? "",
    e.regenPerSec ?? "",
    k.includes("Slowing") ? SLOWING_SEC.Silver : "",
    k.includes("Recharge") ? RECHARGE_SEC.Silver : "",
    k.includes("Fasting") ? FASTING_SEC.Silver : "",
    l?.direction ?? "",
    l?.damage ?? "",
    l?.shield ?? "",
    l?.healingPct ?? "",
    l?.vampirismPct ?? "",
    l?.cooldownReductionPct ?? "",
    l?.globalTarget ?? "",
    it.heavy ? 1 : 0,
    `/sprites/items/${it.id}.png`,
    hasItemSprite(it.id) ? 1 : 0,
    it.description,
  ];
}

// ─── Write CSV ──────────────────────────────────────────────────────────────
async function writeCsv() {
  const lines = [COLS.join(",")];
  for (const it of ITEMS) {
    lines.push(rowFor(it).map(csvEscape).join(","));
  }
  await fs.writeFile(path.join(OUT, "items.csv"), lines.join("\n") + "\n");
  console.log(`Wrote catalog/items.csv  (${ITEMS.length} items)`);
}

// ─── Write Markdown ─────────────────────────────────────────────────────────
async function writeMarkdown() {
  const groups = new Map<string, typeof ITEMS>();
  for (const it of ITEMS) {
    const arr = groups.get(it.natureType) ?? [];
    arr.push(it);
    groups.set(it.natureType, arr);
  }

  const lines: string[] = [];
  lines.push(`# Mythic Market — Item Catalog`);
  lines.push(``);
  lines.push(`_Auto-generated by \`npm run catalog\`. ${ITEMS.length} items total._`);
  lines.push(``);
  lines.push(`Primary effect magnitudes (Damage / Shield / Healing) are read directly`);
  lines.push(`from the rarity table at runtime — they're identical for every item that`);
  lines.push(`carries the keyword. Item identity comes from cooldown + keyword combos`);
  lines.push(`+ link bonuses + status-effect stacks (Burn / Poison / Regen).`);
  lines.push(``);

  // Rarity reference table
  lines.push(`## Rarity reference`);
  lines.push(``);
  lines.push(`| Effect | Wooden | Bronze | Silver | Gold | Diamond |`);
  lines.push(`|---|---|---|---|---|---|`);
  for (const key of ["Damage", "Shield", "Healing", "Overhealing"] as const) {
    const t = EFFECT_TABLE[key];
    lines.push(`| **${key}** | ${t.Wooden} | ${t.Bronze} | ${t.Silver} | ${t.Gold} | ${t.Diamond} |`);
  }
  lines.push(`| **Vampirism %** | ${VAMPIRISM_PCT.Wooden} | ${VAMPIRISM_PCT.Bronze} | ${VAMPIRISM_PCT.Silver} | ${VAMPIRISM_PCT.Gold} | ${VAMPIRISM_PCT.Diamond} |`);
  lines.push(`| **Slowing s** | ${SLOWING_SEC.Wooden} | ${SLOWING_SEC.Bronze} | ${SLOWING_SEC.Silver} | ${SLOWING_SEC.Gold} | ${SLOWING_SEC.Diamond} |`);
  lines.push(`| **Recharge s** | ${RECHARGE_SEC.Wooden} | ${RECHARGE_SEC.Bronze} | ${RECHARGE_SEC.Silver} | ${RECHARGE_SEC.Gold} | ${RECHARGE_SEC.Diamond} |`);
  lines.push(`| **Fasting dur s** | ${FASTING_SEC.Wooden} | ${FASTING_SEC.Bronze} | ${FASTING_SEC.Silver} | ${FASTING_SEC.Gold} | ${FASTING_SEC.Diamond} |`);
  lines.push(`| **Burn dmg/tick** | ${BURN_TICK_DPS.Wooden} | ${BURN_TICK_DPS.Bronze} | ${BURN_TICK_DPS.Silver} | ${BURN_TICK_DPS.Gold} | ${BURN_TICK_DPS.Diamond} |`);
  lines.push(`| **Poison dmg/tick** | ${POISON_TICK_DPS.Wooden} | ${POISON_TICK_DPS.Bronze} | ${POISON_TICK_DPS.Silver} | ${POISON_TICK_DPS.Gold} | ${POISON_TICK_DPS.Diamond} |`);
  lines.push(`| **Regen HP/sec** | ${REGEN_PER_SEC.Wooden} | ${REGEN_PER_SEC.Bronze} | ${REGEN_PER_SEC.Silver} | ${REGEN_PER_SEC.Gold} | ${REGEN_PER_SEC.Diamond} |`);
  lines.push(``);

  // Items per nature type
  for (const [nt, arr] of groups) {
    lines.push(`## ${nt} (${arr.length})`);
    lines.push(``);
    lines.push(`| ID | Name | Size | CD | Rarity range | Keywords | Link | Description |`);
    lines.push(`|---|---|---|---|---|---|---|---|`);
    for (const it of arr) {
      const cd = it.baseCooldown >= 100 ? "_passive_" : `${it.baseCooldown}s`;
      const link = it.link
        ? `${it.link.direction}${it.link.damage ? ` +${it.link.damage}dmg` : ""}${it.link.shield ? ` +${it.link.shield}sh` : ""}${it.link.healingPct ? ` +${it.link.healingPct}%heal` : ""}${it.link.vampirismPct ? ` +${it.link.vampirismPct}%vamp` : ""}${it.link.cooldownReductionPct ? ` -${it.link.cooldownReductionPct}%CD` : ""}`
        : "—";
      lines.push(`| \`${it.id}\` | **${it.name}** | ${it.size} | ${cd} | ${it.minRarity}–${it.maxRarity} | ${it.keywords.join(", ") || "—"} | ${link} | ${it.description} |`);
    }
    lines.push(``);
  }

  // Heroes section
  lines.push(`## Heroes (${HEROES.length})`);
  lines.push(``);
  lines.push(`| ID | Name | Nature | Passive | Sprite |`);
  lines.push(`|---|---|---|---|---|`);
  for (const h of HEROES) {
    lines.push(`| \`${h.id}\` | **${h.name}** | ${h.natureType} | ${h.passiveName} — ${h.passiveDescription} | ${hasHeroSprite(h.id) ? "✅" : "SVG"} |`);
  }
  lines.push(``);

  await fs.writeFile(path.join(OUT, "items.md"), lines.join("\n") + "\n");
  console.log(`Wrote catalog/items.md`);
}

async function main() {
  await fs.mkdir(OUT, { recursive: true });
  await writeCsv();
  await writeMarkdown();
  console.log(`Done.`);
}

main().catch((err) => {
  console.error("Catalog export failed:", err);
  process.exit(1);
});
