/**
 * Auto-generated by `npm run art`. Lists which IDs have PNG sprites in
 * /public/sprites/. Components check these sets to decide whether to
 * render an <img> or fall back to the inline SVG glyph.
 *
 * Hand-editing is OK — but if you run the generator it will rewrite
 * this file's `items` and `heroes` arrays.
 */
export const SPRITE_MANIFEST = {
  items: [] as string[],
  heroes: [] as string[],
};

const _items = new Set(SPRITE_MANIFEST.items);
const _heroes = new Set(SPRITE_MANIFEST.heroes);

export function hasItemSprite(id: string): boolean {
  return _items.has(id);
}
export function hasHeroSprite(id: string): boolean {
  return _heroes.has(id);
}
